spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/martial_arts"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/martial_arts"
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

---

#database:
#  driver: org.postgresql.Driver
#  url: "jdbc:postgresql://localhost:5432/students_demo"
#  login: postgres
#  password: root

